server:
  port: 8084

spring:
  application:
    name: ApiGateway

  config:
    import: optional:configserver:http://localhost:8085

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: hotel-service
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**

        - id: rating-service
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
